server:
  port: 8085

spring:
  application:
    name: waterwatch-platform-india
  profiles:
    active: dev
  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:h2:file:./data/waterwatch;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: 

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 30MB

  mail:
    host: localhost
    port: 25
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

  task:
    execution:
      pool:
        core-size: 4
        max-size: 16
        queue-capacity: 100
      thread-name-prefix: waterwatch-task-

waterwatch:
  storage:
    upload-dir: ./uploads
    reports-dir: ./generated-reports
    s3:
      enabled: false
      endpoint: http://localhost:9000
      bucket-name: crowdflow-media
      access-key: minioadmin
      secret-key: minioadmin
  security:
    jwt-secret: "4c7a6e9f1d2b8c5e3a7f9b0c2d4e6f8a1b3c5e7d9f0a2b4c6e8d0f2a4b6c8e0"
    jwt-expiration-ms: 86400000 # 24 hours
  clustering:
    eps-meters: 150.0
    min-points: 3
    escalation-threshold: 5
    cron-enabled: true
    cron-expression: "0 */2 * * * *"
  dispatch:
    simulation-mode: true
    default-sender-email: alerts@waterwatch.civic.gov.in
    webhook-timeout-ms: 4000
  geo:
    country: "India"
    default-lat: 28.6320
    default-lon: 77.2105
    default-city: "National Capital Territory of Delhi, India"
    helpline: "1916"

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
